name: unit_tests

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:

    - name: Clone Main Repository
      uses: actions/checkout@v2

    - name: Clone Submodule - PMwCAS
      uses: actions/checkout@v2
      with:
        repository: dbgroup-nagoya-u/pmwcas
        path: external/pmwcas
        ssh-key: ${{secrets.SSH_KEY}}
        persist-credentials: false

    - name: Clone Submodule - GoogleTest
      uses: actions/checkout@v2
      with:
        repository: google/googletest
        path: external/googletest

    - name: Create Build Environment
      shell: bash
      run: |
        apt update && apt install -y build-essential cmake libnuma-dev
        cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBZTREE_BUILD_TESTS=on

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE
