name: Ubuntu-20.04

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:

    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{secrets.SSH_KEY_FOR_ACTIONS}}
        persist-credentials: false

    - name: Create Build Environment
      shell: bash
      run: |
        sudo apt-get install -y build-essential cmake
        cmake -E make_directory ${{github.workspace}}/build_4k
        cmake -E make_directory ${{github.workspace}}/build_8k

    - name: Configure CMake for 4K Pages
      shell: bash
      working-directory: ${{github.workspace}}/build_4k
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBZTREE_PAGE_SIZE=4096 -DBZTREE_MAX_UNSORTED_REC_NUM=32 -DBZTREE_BUILD_TESTS=on -DBZTREE_TEST_THREAD_NUM=2

    - name: Build for 4K Pages
      shell: bash
      working-directory: ${{github.workspace}}/build_4k
      run: cmake --build . --parallel 2 --config $BUILD_TYPE

    - name: Test for 4K Pages
      shell: bash
      working-directory: ${{github.workspace}}/build_4k
      run: ctest -C $BUILD_TYPE

    - name: Configure CMake for 8K Pages
      shell: bash
      working-directory: ${{github.workspace}}/build_8k
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBZTREE_PAGE_SIZE=8192 -DBZTREE_MAX_UNSORTED_REC_NUM=64 -DBZTREE_BUILD_TESTS=on -DBZTREE_TEST_THREAD_NUM=2

    - name: Build for 8K Pages
      shell: bash
      working-directory: ${{github.workspace}}/build_8k
      run: cmake --build . --parallel 2 --config $BUILD_TYPE

    - name: Test for 8K Pages
      shell: bash
      working-directory: ${{github.workspace}}/build_8k
      run: ctest -C $BUILD_TYPE
